# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
